# permissions for end users to edit customtypes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customtype-editor-role
rules:
- apiGroups:
  - zhhnzw.mock.com
  resources:
  - customtypes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zhhnzw.mock.com
  resources:
  - customtypes/status
  verbs:
  - get
