# permissions for end users to view customtypes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customtype-viewer-role
rules:
- apiGroups:
  - zhhnzw.mock.com
  resources:
  - customtypes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zhhnzw.mock.com
  resources:
  - customtypes/status
  verbs:
  - get
