
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - zhhnzw.mock.com
  resources:
  - custompods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zhhnzw.mock.com
  resources:
  - custompods/finalizers
  verbs:
  - update
- apiGroups:
  - zhhnzw.mock.com
  resources:
  - custompods/status
  verbs:
  - get
  - patch
  - update
