# permissions for end users to view custompods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custompod-viewer-role
rules:
- apiGroups:
  - zhhnzw.mock.com
  resources:
  - custompods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zhhnzw.mock.com
  resources:
  - custompods/status
  verbs:
  - get
