# permissions for end users to edit custompods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custompod-editor-role
rules:
- apiGroups:
  - zhhnzw.mock.com
  resources:
  - custompods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zhhnzw.mock.com
  resources:
  - custompods/status
  verbs:
  - get
